name: update course data

on:
  schedule:
  - cron: '0 0 * * *'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: checkout repo
      uses: actions/checkout@v3

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: pull from roster API
      run: python src/course-scraper.py

    - name: commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Github Action"
        git add .
        git commit -m "update classes.json"

    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main 

    - name: setup node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: install node packages
      run: npm install

    - name: build page
      run: npm run build

    - name: deploy to gh-pages 
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build